zookeeper:
  image: awesomedata/zookeeper
  hostname: zookeeper
  container_name: zookeeper
  domainname: hadoop
  net: hadoop
  ports:
    - "2181"

kafka1:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka1
  container_name: kafka1
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka2:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka2
  container_name: kafka2
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka3:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka3
  container_name: kafka3
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock